name: Release
on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ada-actions/toolchain@dev
        with:
          distrib: fsf
          target: native
      - run: make
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
